### ISSUE TITLE
updated ebuild

### ISSUE THREAD

**Issue by ghost** [thrasibule/thrasibule-overlay#1]
Hi.

Are you planning to do a 2.4.5 pjsip ebuild?

thanks so far and cheers.

**Comment by thrasibule** [comment]
I've pushed a new ebuild for pjsip let me know if it works for you.

**Comment by ghost** [comment]
Thanks. Will testing soonish.

cheers

**Comment by ghost** [comment]
Hi. Just tested this with asterisk 13.6.0. Works!

thanks and cheers
